# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Storm Mata
# Description of the Site
description: Wind energy and atmospheric boundary layer physics
# URL of Image of the Site
site-image: /assets/images/bg1Crop.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/android-chrome-512x512.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/bg1Crop.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: storm@mit.edu
facebook_username:
twitter_username: 
instagram_username:
linkedin_username: thedevslot
github_username:  thedevslot
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Storm Mata
# URL for the Image of the Author
author-image: /assets/images/mata2022_storm(3).jpeg
# 60 Words About the Author
author-about: >
  I am a graduate researcher in the <a href="https://www.howlandlab.com/" target="_blank">Howland Lab</a> at the Massachusetts Institute of Technology.
  My work combines theoretical and experimental environmental fluid mechanics with atmospheric modeling for more efficient wind energy generation systems.
  My work is currently supported by the <a href="https://www.krellinst.org/csgf/">Department of Energy Computational Science Graduate Fellowship</a>.
  <br><br>
  I completed my undergraduate degree in Engineering Sciences from Dartmouth College in 2019. My undergraduate studies were supported by the
  <a href="https://gmsp.org">Gates Millennium Scholars Program</a>. Before entering graduate school, I worked for several years in
  energy engineering and consulting, ensuring regulatory compliance with emissions and sustainability laws in New York City.
  <br><br>
  Outside of research, I serve on the Department of Civil and Environmental Engineering <a href="https://cee.mit.edu/about/belonging-and-achievement/">Belonging, Achievement, and Composition Committee</a>
  and the MIT School of Engineering <a href="https://engineering.mit.edu/about/leadership/graduate-student-advisory-group/">Graduate Student Advisory Group</a>.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
